services:
    netgen_open_graph.templating.twig.extension:
        class: Netgen\Bundle\OpenGraphBundle\Templating\Twig\Extension\NetgenOpenGraphExtension
        public: false
        arguments:
            - "@netgen_open_graph.meta_tag_collector"
            - "@netgen_open_graph.meta_tag_renderer"
            - "@?logger"
        calls:
            - [setThrowExceptions, ["%kernel.debug%"]]
        tags:
            - { name: twig.extension }
