filter:
    paths:
        - 'bundle/*'
    excluded_paths:
        - 'tests/*'
        - 'vendor/*'
        - 'build/*'
tools:
    php_analyzer: true
    sensiolabs_security_checker: true
checks:
    php: true
